#!/bin/bash
#install java8
sudo add-apt-repository -y ppa:openjdk-r/ppa
sudo apt update
sudo apt install openjdk-11-jdk openjdk-11-jre 
java -version



# install jenkins 
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
sudo apt update
sudo apt install jenkins
sudo systemctl start jenkins
